#!/bin/bash

docker run -ti --rm \
           -e DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v ~/.eclipse-docker/workspace:/home/developer/workspace \
           -v ~/git:/home/developer/git \
           -v ~/.m2:/home/developer/.m2 \
           mvberg/eclipse:4.2.2
