#!/bin/bash

ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')

mkdir -p .eclipse-docker

docker run -ti --rm \
           --cpus=0.000 \
           -e DISPLAY=$ip:0 \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v ~/.eclipse-docker/workspace:/home/developer/workspace \
           -v ~/git:/home/developer/git \
           -v ~/.m2:/home/developer/.m2 \
           -v ~/.ssh:/home/developer/.ssh \
           barchart/eclipse:v4.2.2
